// spotless:off
package frc.robot.constants;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import java.util.Map;
import java.util.OptionalInt;

import choreo.auto.AutoRoutine;
import choreo.auto.AutoTrajectory;
// If the 2 imports above cause errors because you're not using ChoreoLib,
// turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.

/**
 * A class containing the name, start pose, end pose, and total time of every Choreo trajectory.
 * This prevents your code from referencing deleted or misspelled trajectories,
 * and removes the need for JSON parsing to load a trajectory's essential data.
 * DO NOT MODIFY THIS FILE YOURSELF! It is automatically generated by Choreo.
 */
public record ChoreoTraj(
    String name,
    OptionalInt segment,
    double totalTimeSecs,
    Pose2d initialPoseBlue,
    Pose2d endPoseBlue
) {
    public static final ChoreoTraj xPreviewPreloadDepotOutpost = new ChoreoTraj(
        "xPreviewPreloadDepotOutpost",
        OptionalInt.empty(),
        2.9149,
        new Pose2d(3.64442, 5.95939, Rotation2d.fromRadians(0)),
        new Pose2d(0.74877, 0.82106, Rotation2d.fromRadians(0))
    );
    public static final ChoreoTraj xPreviewFirstDSideTrenchNeutral = new ChoreoTraj(
        "xPreviewFirstDSideTrenchNeutral",
        OptionalInt.empty(),
        5.67607,
        new Pose2d(4.12706, 7.65828, Rotation2d.fromRadians(1.5708)),
        new Pose2d(3.3141, 5.37187, Rotation2d.fromRadians(0.5236))
    );
    public static final ChoreoTraj FirstDSideNeutralToAlliance = new ChoreoTraj(
        "FirstDSideNeutralToAlliance",
        OptionalInt.empty(),
        2.42112,
        new Pose2d(7.84374, 4.53587, Rotation2d.fromRadians(1.5708)),
        new Pose2d(3.3141, 5.37187, Rotation2d.fromRadians(0.5236))
    );
    public static final ChoreoTraj OSideAllianceToOutpost = new ChoreoTraj(
        "OSideAllianceToOutpost",
        OptionalInt.empty(),
        1.57579,
        new Pose2d(3.3141, 2.69813, Rotation2d.fromRadians(-0.5236)),
        new Pose2d(0.39741, 0.66858, Rotation2d.fromRadians(0))
    );
    public static final ChoreoTraj SecondOSideNeutralToAlliance = new ChoreoTraj(
        "SecondOSideNeutralToAlliance",
        OptionalInt.empty(),
        3.35108,
        new Pose2d(7.84374, 3.53413, Rotation2d.fromRadians(-1.5708)),
        new Pose2d(3.3141, 2.69813, Rotation2d.fromRadians(-0.5236))
    );
    public static final ChoreoTraj xPreviewSecondOSideTrenchNeutral = new ChoreoTraj(
        "xPreviewSecondOSideTrenchNeutral",
        OptionalInt.empty(),
        6.5858,
        new Pose2d(4.12706, 0.41172, Rotation2d.fromRadians(-1.5708)),
        new Pose2d(3.3141, 2.69813, Rotation2d.fromRadians(-0.5236))
    );
    public static final ChoreoTraj DSideAllianceToTrench = new ChoreoTraj(
        "DSideAllianceToTrench",
        OptionalInt.empty(),
        1.41441,
        new Pose2d(3.3141, 5.37187, Rotation2d.fromRadians(0.5236)),
        new Pose2d(4.12706, 7.65828, Rotation2d.fromRadians(1.5708))
    );
    public static final ChoreoTraj DSideBumpToDepot = new ChoreoTraj(
        "DSideBumpToDepot",
        OptionalInt.empty(),
        1.14827,
        new Pose2d(3.64442, 5.95939, Rotation2d.fromRadians(0)),
        new Pose2d(0.68343, 5.97907, Rotation2d.fromRadians(0))
    );
    public static final ChoreoTraj xPreviewOSidePreloadAndBackup = new ChoreoTraj(
        "xPreviewOSidePreloadAndBackup",
        OptionalInt.empty(),
        1.33437,
        new Pose2d(3.58253, 4.02943, Rotation2d.fromRadians(0)),
        new Pose2d(0.4406, 1.92714, Rotation2d.fromRadians(0))
    );
    public static final ChoreoTraj xPreviewPreloadDepot = new ChoreoTraj(
        "xPreviewPreloadDepot",
        OptionalInt.empty(),
        1.93922,
        new Pose2d(3.74442, 5.95939, Rotation2d.fromRadians(0)),
        new Pose2d(0.67815, 7.4473, Rotation2d.fromRadians(0))
    );
    public static final ChoreoTraj DepotToOutpost = new ChoreoTraj(
        "DepotToOutpost",
        OptionalInt.empty(),
        1.76382,
        new Pose2d(0.78688, 5.95277, Rotation2d.fromRadians(0)),
        new Pose2d(0.74877, 0.82106, Rotation2d.fromRadians(0))
    );
    public static final ChoreoTraj xPreview4414DSideTrenchNeutral = new ChoreoTraj(
        "xPreview4414DSideTrenchNeutral",
        OptionalInt.empty(),
        8.52061,
        new Pose2d(4.12706, 7.65828, Rotation2d.fromRadians(1.5708)),
        new Pose2d(0.40031, 6.923, Rotation2d.fromRadians(-1.5708))
    );
    public static final ChoreoTraj SecondDSideNeutralToAlliance = new ChoreoTraj(
        "SecondDSideNeutralToAlliance",
        OptionalInt.empty(),
        3.31265,
        new Pose2d(7.84374, 4.53587, Rotation2d.fromRadians(1.5708)),
        new Pose2d(3.3141, 5.37187, Rotation2d.fromRadians(0.5236))
    );
    public static final ChoreoTraj OSidePreloadAndBackup = new ChoreoTraj(
        "OSidePreloadAndBackup",
        OptionalInt.empty(),
        1.33437,
        new Pose2d(3.58253, 4.02943, Rotation2d.fromRadians(0)),
        new Pose2d(0.4406, 1.92714, Rotation2d.fromRadians(0))
    );
    public static final ChoreoTraj OSideTrenchToNeutral = new ChoreoTraj(
        "OSideTrenchToNeutral",
        OptionalInt.empty(),
        3.39378,
        new Pose2d(4.12706, 0.41172, Rotation2d.fromRadians(-1.5708)),
        new Pose2d(7.84374, 3.53413, Rotation2d.fromRadians(-1.5708))
    );
    public static final ChoreoTraj OSideAllianceToTrench = new ChoreoTraj(
        "OSideAllianceToTrench",
        OptionalInt.empty(),
        1.41441,
        new Pose2d(3.3141, 2.69813, Rotation2d.fromRadians(-0.5236)),
        new Pose2d(4.12706, 0.41172, Rotation2d.fromRadians(-1.5708))
    );
    public static final ChoreoTraj xPreviewSecondDSideTrenchNeutral = new ChoreoTraj(
        "xPreviewSecondDSideTrenchNeutral",
        OptionalInt.empty(),
        6.52944,
        new Pose2d(4.12706, 7.65828, Rotation2d.fromRadians(1.5708)),
        new Pose2d(3.3141, 5.37187, Rotation2d.fromRadians(0.5236))
    );
    public static final ChoreoTraj AutoPIDTuning = new ChoreoTraj(
        "AutoPIDTuning",
        OptionalInt.empty(),
        1.15674,
        new Pose2d(3.57341, 6.05182, Rotation2d.fromRadians(0)),
        new Pose2d(3.57341, 3.05182, Rotation2d.fromRadians(0))
    );
    public static final ChoreoTraj FirstOSideNeutralToAlliance = new ChoreoTraj(
        "FirstOSideNeutralToAlliance",
        OptionalInt.empty(),
        2.42112,
        new Pose2d(7.84374, 3.53413, Rotation2d.fromRadians(-1.5708)),
        new Pose2d(3.3141, 2.69813, Rotation2d.fromRadians(-0.5236))
    );
    public static final ChoreoTraj xPreviewFirstOSideTrenchNeutral = new ChoreoTraj(
        "xPreviewFirstOSideTrenchNeutral",
        OptionalInt.empty(),
        5.67607,
        new Pose2d(4.12706, 0.41172, Rotation2d.fromRadians(-1.5708)),
        new Pose2d(3.3141, 2.69813, Rotation2d.fromRadians(-0.5236))
    );
    public static final ChoreoTraj DSideAllianceToDepot = new ChoreoTraj(
        "DSideAllianceToDepot",
        OptionalInt.empty(),
        2.50806,
        new Pose2d(3.3141, 5.37187, Rotation2d.fromRadians(0.5236)),
        new Pose2d(0.40031, 6.923, Rotation2d.fromRadians(-1.5708))
    );
    public static final ChoreoTraj DSideTrenchToNeutral = new ChoreoTraj(
        "DSideTrenchToNeutral",
        OptionalInt.empty(),
        3.37498,
        new Pose2d(4.12706, 7.65828, Rotation2d.fromRadians(1.5708)),
        new Pose2d(7.84374, 4.53587, Rotation2d.fromRadians(1.5708))
    );
    public static final ChoreoTraj PreloadAndBackupTower = new ChoreoTraj(
        "PreloadAndBackupTower",
        OptionalInt.empty(),
        0.95141,
        new Pose2d(3.58253, 4.02943, Rotation2d.fromRadians(0)),
        new Pose2d(1.54855, 4.02943, Rotation2d.fromRadians(0))
    );
    public static final ChoreoTraj DepotToCorner = new ChoreoTraj(
        "DepotToCorner",
        OptionalInt.empty(),
        0.8504,
        new Pose2d(0.68343, 5.97907, Rotation2d.fromRadians(0)),
        new Pose2d(0.59227, 7.60044, Rotation2d.fromRadians(0))
    );
    public static final ChoreoTraj xPreviewOSideTrenchNeutralOutpost = new ChoreoTraj(
        "xPreviewOSideTrenchNeutralOutpost",
        OptionalInt.empty(),
        8.00154,
        new Pose2d(4.12706, 0.41172, Rotation2d.fromRadians(-1.5708)),
        new Pose2d(0.39741, 0.66858, Rotation2d.fromRadians(0))
    );
    public static final ChoreoTraj xPreviewPreloadAndBackup = new ChoreoTraj(
        "xPreviewPreloadAndBackup",
        OptionalInt.empty(),
        0.95141,
        new Pose2d(3.58253, 4.02943, Rotation2d.fromRadians(0)),
        new Pose2d(1.54855, 4.02943, Rotation2d.fromRadians(0))
    );

    /**
     * A map between trajectory names and their corresponding data.
     * This allows for trajectory data to be looked up with strings during runtime.
     */
    public static final Map<String, ChoreoTraj> ALL_TRAJECTORIES = Map.ofEntries(
        Map.entry("xPreviewPreloadDepotOutpost", xPreviewPreloadDepotOutpost),
        Map.entry("xPreviewFirstDSideTrenchNeutral", xPreviewFirstDSideTrenchNeutral),
        Map.entry("FirstDSideNeutralToAlliance", FirstDSideNeutralToAlliance),
        Map.entry("OSideAllianceToOutpost", OSideAllianceToOutpost),
        Map.entry("SecondOSideNeutralToAlliance", SecondOSideNeutralToAlliance),
        Map.entry("xPreviewSecondOSideTrenchNeutral", xPreviewSecondOSideTrenchNeutral),
        Map.entry("DSideAllianceToTrench", DSideAllianceToTrench),
        Map.entry("DSideBumpToDepot", DSideBumpToDepot),
        Map.entry("xPreviewOSidePreloadAndBackup", xPreviewOSidePreloadAndBackup),
        Map.entry("xPreviewPreloadDepot", xPreviewPreloadDepot),
        Map.entry("DepotToOutpost", DepotToOutpost),
        Map.entry("xPreview4414DSideTrenchNeutral", xPreview4414DSideTrenchNeutral),
        Map.entry("SecondDSideNeutralToAlliance", SecondDSideNeutralToAlliance),
        Map.entry("OSidePreloadAndBackup", OSidePreloadAndBackup),
        Map.entry("OSideTrenchToNeutral", OSideTrenchToNeutral),
        Map.entry("OSideAllianceToTrench", OSideAllianceToTrench),
        Map.entry("xPreviewSecondDSideTrenchNeutral", xPreviewSecondDSideTrenchNeutral),
        Map.entry("AutoPIDTuning", AutoPIDTuning),
        Map.entry("FirstOSideNeutralToAlliance", FirstOSideNeutralToAlliance),
        Map.entry("xPreviewFirstOSideTrenchNeutral", xPreviewFirstOSideTrenchNeutral),
        Map.entry("DSideAllianceToDepot", DSideAllianceToDepot),
        Map.entry("DSideTrenchToNeutral", DSideTrenchToNeutral),
        Map.entry("PreloadAndBackupTower", PreloadAndBackupTower),
        Map.entry("DepotToCorner", DepotToCorner),
        Map.entry("xPreviewOSideTrenchNeutralOutpost", xPreviewOSideTrenchNeutralOutpost),
        Map.entry("xPreviewPreloadAndBackup", xPreviewPreloadAndBackup)
    );

    /**
     * Looks up the ChoreoTraj segment of the given overall ChoreoTraj.
     * WARNING: will raise an exception if not called with a valid segment index.
     */
    public ChoreoTraj segment(int segment) {
        var traj = ChoreoTraj.ALL_TRAJECTORIES.get(this.name + "$" + segment);
        if (traj == null) {
            throw new NullPointerException("Trajectory " + this.name + " does not have segment #" + segment + ".");
        }
        return traj;
    }
    
    // If these methods cause errors because you're not using ChoreoLib,
    // turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
    /**
     * Load an AutoTrajectory directly from a ChoreoTraj, which may be a segment of a larger trajectory.
     */
    public AutoTrajectory asAutoTraj(AutoRoutine routine) {
        if (this.segment.isPresent()) {
            return routine.trajectory(this.name, this.segment.getAsInt());
        }
        return routine.trajectory(this.name);
    }
}
// spotless:on
