// spotless:off
package frc.robot.constants;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import java.util.Map;
import java.util.OptionalInt;

import choreo.auto.AutoRoutine;
import choreo.auto.AutoTrajectory;
// If the 2 imports above cause errors because you're not using ChoreoLib,
// turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.

/**
 * A class containing the name, start pose, end pose, and total time of every
 * Choreo trajectory.
 * This prevents your code from referencing deleted or misspelled trajectories,
 * and removes the need for JSON parsing to load a trajectory's essential data.
 * DO NOT MODIFY THIS FILE YOURSELF! It is automatically generated by Choreo.
 */
public record ChoreoTraj(
    String name,
    OptionalInt segment,
    double totalTimeSecs,
    Pose2d initialPoseBlue,
    Pose2d endPoseBlue) {

  public static final ChoreoTraj AutoPIDTuning = new ChoreoTraj(
      "AutoPIDTuning",
      OptionalInt.empty(),
      1.15674,
      new Pose2d(3.573, 6.052, Rotation2d.fromRadians(0)),
      new Pose2d(3.573, 3.052, Rotation2d.fromRadians(0)));
  public static final ChoreoTraj DepotToCorner = new ChoreoTraj(
      "DepotToCorner",
      OptionalInt.empty(),
      0.60364,
      new Pose2d(0.683, 5.979, Rotation2d.fromRadians(0)),
      new Pose2d(0.592, 7.6, Rotation2d.fromRadians(0)));
  public static final ChoreoTraj DepotToOutpost = new ChoreoTraj(
      "DepotToOutpost",
      OptionalInt.empty(),
      3.36206,
      new Pose2d(0.787, 5.953, Rotation2d.fromRadians(0)),
      new Pose2d(0.397, 0.669, Rotation2d.fromRadians(0)));
  public static final ChoreoTraj DSideAllianceToDepot = new ChoreoTraj(
      "DSideAllianceToDepot",
      OptionalInt.empty(),
      2.17645,
      new Pose2d(3.314, 5.372, Rotation2d.fromRadians(0.524)),
      new Pose2d(0.4, 6.923, Rotation2d.fromRadians(-1.571)));
  public static final ChoreoTraj DSideAllianceToTrench = new ChoreoTraj(
      "DSideAllianceToTrench",
      OptionalInt.empty(),
      1.16872,
      new Pose2d(3.314, 5.372, Rotation2d.fromRadians(0.524)),
      new Pose2d(4.127, 7.658, Rotation2d.fromRadians(1.571)));
  public static final ChoreoTraj DSideBumpToDepot = new ChoreoTraj(
      "DSideBumpToDepot",
      OptionalInt.empty(),
      1.9323,
      new Pose2d(3.644, 5.959, Rotation2d.fromRadians(0)),
      new Pose2d(0.683, 5.979, Rotation2d.fromRadians(0)));
  public static final ChoreoTraj DSideCornerToDSideTrench = new ChoreoTraj(
      "DSideCornerToDSideTrench",
      OptionalInt.empty(),
      1.34803,
      new Pose2d(0.4, 6.923, Rotation2d.fromRadians(-1.571)),
      new Pose2d(4.127, 7.658, Rotation2d.fromRadians(1.571)));
  public static final ChoreoTraj DSideTrenchToNeutral = new ChoreoTraj(
      "DSideTrenchToNeutral",
      OptionalInt.empty(),
      3.01616,
      new Pose2d(4.127, 7.658, Rotation2d.fromRadians(1.571)),
      new Pose2d(7.844, 4.536, Rotation2d.fromRadians(1.571)));
  public static final ChoreoTraj FirstDSideNeutralToAlliance = new ChoreoTraj(
      "FirstDSideNeutralToAlliance",
      OptionalInt.empty(),
      2.06375,
      new Pose2d(7.844, 4.536, Rotation2d.fromRadians(1.571)),
      new Pose2d(3.314, 5.372, Rotation2d.fromRadians(0.524)));
  public static final ChoreoTraj FirstOSideNeutralToAlliance = new ChoreoTraj(
      "FirstOSideNeutralToAlliance",
      OptionalInt.empty(),
      2.06375,
      new Pose2d(7.844, 3.534, Rotation2d.fromRadians(-1.571)),
      new Pose2d(3.314, 2.698, Rotation2d.fromRadians(-0.524)));
  public static final ChoreoTraj OSideAllianceToOutpost = new ChoreoTraj(
      "OSideAllianceToOutpost",
      OptionalInt.empty(),
      2.35462,
      new Pose2d(3.314, 2.698, Rotation2d.fromRadians(-0.524)),
      new Pose2d(0.397, 0.669, Rotation2d.fromRadians(0)));
  public static final ChoreoTraj OSideAllianceToTrench = new ChoreoTraj(
      "OSideAllianceToTrench",
      OptionalInt.empty(),
      0.95616,
      new Pose2d(3.314, 2.698, Rotation2d.fromRadians(-0.524)),
      new Pose2d(4.127, 0.412, Rotation2d.fromRadians(-1.571)));
  public static final ChoreoTraj OSidePreloadAndBackup = new ChoreoTraj(
      "OSidePreloadAndBackup",
      OptionalInt.empty(),
      1.06225,
      new Pose2d(3.583, 4.029, Rotation2d.fromRadians(0)),
      new Pose2d(0.441, 1.927, Rotation2d.fromRadians(0)));
  public static final ChoreoTraj OSideTrenchToNeutral = new ChoreoTraj(
      "OSideTrenchToNeutral",
      OptionalInt.empty(),
      3.035,
      new Pose2d(4.127, 0.412, Rotation2d.fromRadians(-1.571)),
      new Pose2d(7.844, 3.534, Rotation2d.fromRadians(-1.571)));
  public static final ChoreoTraj PreloadAndBackupTower = new ChoreoTraj(
      "PreloadAndBackupTower",
      OptionalInt.empty(),
      0.95141,
      new Pose2d(3.583, 4.029, Rotation2d.fromRadians(0)),
      new Pose2d(1.549, 4.029, Rotation2d.fromRadians(0)));
  public static final ChoreoTraj SecondDSideNeutralToAlliance = new ChoreoTraj(
      "SecondDSideNeutralToAlliance",
      OptionalInt.empty(),
      2.95501,
      new Pose2d(7.844, 4.536, Rotation2d.fromRadians(1.571)),
      new Pose2d(3.314, 5.372, Rotation2d.fromRadians(0.524)));
  public static final ChoreoTraj SecondOSideNeutralToAlliance = new ChoreoTraj(
      "SecondOSideNeutralToAlliance",
      OptionalInt.empty(),
      2.99336,
      new Pose2d(7.844, 3.534, Rotation2d.fromRadians(-1.571)),
      new Pose2d(3.314, 2.698, Rotation2d.fromRadians(-0.524)));
  public static final ChoreoTraj xPreview4414DSideTrenchNeutral = new ChoreoTraj(
      "xPreview4414DSideTrenchNeutral",
      OptionalInt.empty(),
      8.51942,
      new Pose2d(4.127, 7.658, Rotation2d.fromRadians(1.571)),
      new Pose2d(0.4, 6.923, Rotation2d.fromRadians(-1.571)));
  public static final ChoreoTraj xPreviewFirstDSideTrenchNeutral = new ChoreoTraj(
      "xPreviewFirstDSideTrenchNeutral",
      OptionalInt.empty(),
      5.67607,
      new Pose2d(4.127, 7.658, Rotation2d.fromRadians(1.571)),
      new Pose2d(3.314, 5.372, Rotation2d.fromRadians(0.524)));
  public static final ChoreoTraj xPreviewFirstOSideTrenchNeutral = new ChoreoTraj(
      "xPreviewFirstOSideTrenchNeutral",
      OptionalInt.empty(),
      5.67607,
      new Pose2d(4.127, 0.412, Rotation2d.fromRadians(-1.571)),
      new Pose2d(3.314, 2.698, Rotation2d.fromRadians(-0.524)));
  public static final ChoreoTraj xPreviewOSidePreloadAndBackup = new ChoreoTraj(
      "xPreviewOSidePreloadAndBackup",
      OptionalInt.empty(),
      1.33437,
      new Pose2d(3.583, 4.029, Rotation2d.fromRadians(0)),
      new Pose2d(0.441, 1.927, Rotation2d.fromRadians(0)));
  public static final ChoreoTraj xPreviewOSideTrenchNeutralOutpost = new ChoreoTraj(
      "xPreviewOSideTrenchNeutralOutpost",
      OptionalInt.empty(),
      8.00154,
      new Pose2d(4.127, 0.412, Rotation2d.fromRadians(-1.571)),
      new Pose2d(0.397, 0.669, Rotation2d.fromRadians(0)));
  public static final ChoreoTraj xPreviewPreloadAndBackup = new ChoreoTraj(
      "xPreviewPreloadAndBackup",
      OptionalInt.empty(),
      0.95141,
      new Pose2d(3.583, 4.029, Rotation2d.fromRadians(0)),
      new Pose2d(1.549, 4.029, Rotation2d.fromRadians(0)));
  public static final ChoreoTraj xPreviewPreloadDepot = new ChoreoTraj(
      "xPreviewPreloadDepot",
      OptionalInt.empty(),
      1.93922,
      new Pose2d(3.744, 5.959, Rotation2d.fromRadians(0)),
      new Pose2d(0.678, 7.447, Rotation2d.fromRadians(0)));
  public static final ChoreoTraj xPreviewPreloadDepotOutpost = new ChoreoTraj(
      "xPreviewPreloadDepotOutpost",
      OptionalInt.empty(),
      2.9149,
      new Pose2d(3.644, 5.959, Rotation2d.fromRadians(0)),
      new Pose2d(0.749, 0.821, Rotation2d.fromRadians(0)));
  public static final ChoreoTraj xPreviewSecondDSideTrenchNeutral = new ChoreoTraj(
      "xPreviewSecondDSideTrenchNeutral",
      OptionalInt.empty(),
      6.52944,
      new Pose2d(4.127, 7.658, Rotation2d.fromRadians(1.571)),
      new Pose2d(3.314, 5.372, Rotation2d.fromRadians(0.524)));
  public static final ChoreoTraj xPreviewSecondOSideTrenchNeutral = new ChoreoTraj(
      "xPreviewSecondOSideTrenchNeutral",
      OptionalInt.empty(),
      6.5858,
      new Pose2d(4.127, 0.412, Rotation2d.fromRadians(-1.571)),
      new Pose2d(3.314, 2.698, Rotation2d.fromRadians(-0.524)));

  /**
   * A map between trajectory names and their corresponding data.
   * This allows for trajectory data to be looked up with strings during runtime.
   */
  public static final Map<String, ChoreoTraj> ALL_TRAJECTORIES = Map.ofEntries(
      Map.entry("AutoPIDTuning", AutoPIDTuning),
      Map.entry("DepotToCorner", DepotToCorner),
      Map.entry("DepotToOutpost", DepotToOutpost),
      Map.entry("DSideAllianceToDepot", DSideAllianceToDepot),
      Map.entry("DSideAllianceToTrench", DSideAllianceToTrench),
      Map.entry("DSideBumpToDepot", DSideBumpToDepot),
      Map.entry("DSideCornerToDSideTrench", DSideCornerToDSideTrench),
      Map.entry("DSideTrenchToNeutral", DSideTrenchToNeutral),
      Map.entry("FirstDSideNeutralToAlliance", FirstDSideNeutralToAlliance),
      Map.entry("FirstOSideNeutralToAlliance", FirstOSideNeutralToAlliance),
      Map.entry("HubToDepot", HubToDepot),
      Map.entry("HubToOutpost", HubToOutpost),
      Map.entry("OSideAllianceToOutpost", OSideAllianceToOutpost),
      Map.entry("OSideAllianceToTrench", OSideAllianceToTrench),
      Map.entry("OSidePreloadAndBackup", OSidePreloadAndBackup),
      Map.entry("OSideTrenchToNeutral", OSideTrenchToNeutral),
      Map.entry("PreloadAndBackupTower", PreloadAndBackupTower),
      Map.entry("SecondDSideNeutralToAlliance", SecondDSideNeutralToAlliance),
      Map.entry("SecondOSideNeutralToAlliance", SecondOSideNeutralToAlliance),
      Map.entry("xPreview4414DSideTrenchNeutral", xPreview4414DSideTrenchNeutral),
      Map.entry("xPreviewFirstDSideTrenchNeutral", xPreviewFirstDSideTrenchNeutral),
      Map.entry("xPreviewFirstOSideTrenchNeutral", xPreviewFirstOSideTrenchNeutral),
      Map.entry("xPreviewOSidePreloadAndBackup", xPreviewOSidePreloadAndBackup),
      Map.entry("xPreviewOSideTrenchNeutralOutpost", xPreviewOSideTrenchNeutralOutpost),
      Map.entry("xPreviewPreloadAndBackup", xPreviewPreloadAndBackup),
      Map.entry("xPreviewPreloadDepot", xPreviewPreloadDepot),
      Map.entry("xPreviewPreloadDepotOutpost", xPreviewPreloadDepotOutpost),
      Map.entry("xPreviewSecondDSideTrenchNeutral", xPreviewSecondDSideTrenchNeutral),
      Map.entry("xPreviewSecondOSideTrenchNeutral", xPreviewSecondOSideTrenchNeutral));

  /**
   * Looks up the ChoreoTraj segment of the given overall ChoreoTraj.
   * WARNING: will raise an exception if not called with a valid segment index.
   */
  public ChoreoTraj segment(int segment) {
    var traj = ChoreoTraj.ALL_TRAJECTORIES.get(this.name + "$" + segment);
    if (traj == null) {
      throw new NullPointerException("Trajectory " + this.name + " does not have segment #" + segment + ".");
    }
    return traj;
  }

  // If these methods cause errors because you're not using ChoreoLib,
  // turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
  /**
   * Load an AutoTrajectory directly from a ChoreoTraj, which may be a segment of
   * a larger trajectory.
   */
  public AutoTrajectory asAutoTraj(AutoRoutine routine) {
    if (this.segment.isPresent()) {
      return routine.trajectory(this.name, this.segment.getAsInt());
    }
    return routine.trajectory(this.name);
  }
}
// spotless:on
