// spotless:off
package frc.robot.constants;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import java.util.Map;
import java.util.OptionalInt;

import choreo.auto.AutoRoutine;
import choreo.auto.AutoTrajectory;
// If the 2 imports above cause errors because you're not using ChoreoLib,
// turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.

/**
 * A class containing the name, start pose, end pose, and total time of every Choreo trajectory.
 * This prevents your code from referencing deleted or misspelled trajectories,
 * and removes the need for JSON parsing to load a trajectory's essential data.
 * DO NOT MODIFY THIS FILE YOURSELF! It is automatically generated by Choreo.
 */
public record ChoreoTraj(
    String name,
    OptionalInt segment,
    double totalTimeSecs,
    Pose2d initialPoseBlue,
    Pose2d endPoseBlue
) {
    public static final ChoreoTraj PreviewOSideTrenchNeutralOutpost = new ChoreoTraj(
        "PreviewOSideTrenchNeutralOutpost",
        OptionalInt.empty(),
        9.05601,
        new Pose2d(4.12706, 0.41172, Rotation2d.fromRadians(-1.5708)),
        new Pose2d(0.39741, 0.66858, Rotation2d.fromRadians(0))
    );
    public static final ChoreoTraj PreviewPreloadDepot = new ChoreoTraj(
        "PreviewPreloadDepot",
        OptionalInt.empty(),
        1.93922,
        new Pose2d(3.74442, 5.95939, Rotation2d.fromRadians(0)),
        new Pose2d(0.67815, 7.4473, Rotation2d.fromRadians(0))
    );
    public static final ChoreoTraj PreviewSecondOSideTrenchNeutral = new ChoreoTraj(
        "PreviewSecondOSideTrenchNeutral",
        OptionalInt.empty(),
        7.64059,
        new Pose2d(4.12706, 0.41172, Rotation2d.fromRadians(-1.5708)),
        new Pose2d(3.3141, 2.69813, Rotation2d.fromRadians(-0.5236))
    );
    public static final ChoreoTraj PreviewPreloadAndBackup = new ChoreoTraj(
        "PreviewPreloadAndBackup",
        OptionalInt.empty(),
        0.95141,
        new Pose2d(3.58253, 4.02943, Rotation2d.fromRadians(0)),
        new Pose2d(1.54855, 4.02943, Rotation2d.fromRadians(0))
    );
    public static final ChoreoTraj Preview4414DSideTrenchNeutral_copy1 = new ChoreoTraj(
        "Preview4414DSideTrenchNeutral_copy1",
        OptionalInt.empty(),
        9.83933,
        new Pose2d(4.12706, 7.65828, Rotation2d.fromRadians(1.5708)),
        new Pose2d(0.40031, 6.923, Rotation2d.fromRadians(-1.5708))
    );
    public static final ChoreoTraj PreviewFirstDSideTrenchNeutral = new ChoreoTraj(
        "PreviewFirstDSideTrenchNeutral",
        OptionalInt.empty(),
        6.56267,
        new Pose2d(4.12706, 7.65828, Rotation2d.fromRadians(1.5708)),
        new Pose2d(3.3141, 5.37187, Rotation2d.fromRadians(0.5236))
    );
    public static final ChoreoTraj PreviewOSidePreloadAndBackup = new ChoreoTraj(
        "PreviewOSidePreloadAndBackup",
        OptionalInt.empty(),
        1.33437,
        new Pose2d(3.58253, 4.02943, Rotation2d.fromRadians(0)),
        new Pose2d(0.4406, 1.92714, Rotation2d.fromRadians(0))
    );
    public static final ChoreoTraj AutoPIDTuning = new ChoreoTraj(
        "AutoPIDTuning",
        OptionalInt.empty(),
        1.15674,
        new Pose2d(3.57341, 6.05182, Rotation2d.fromRadians(0)),
        new Pose2d(3.57341, 3.05182, Rotation2d.fromRadians(0))
    );
    public static final ChoreoTraj PreviewPreloadDepotOutpost = new ChoreoTraj(
        "PreviewPreloadDepotOutpost",
        OptionalInt.empty(),
        2.89169,
        new Pose2d(3.74442, 5.95939, Rotation2d.fromRadians(0)),
        new Pose2d(0.74877, 0.82106, Rotation2d.fromRadians(0))
    );
    public static final ChoreoTraj PreviewFirstOSideTrenchNeutral = new ChoreoTraj(
        "PreviewFirstOSideTrenchNeutral",
        OptionalInt.empty(),
        6.56267,
        new Pose2d(4.12706, 0.41172, Rotation2d.fromRadians(-1.5708)),
        new Pose2d(3.3141, 2.69813, Rotation2d.fromRadians(-0.5236))
    );
    public static final ChoreoTraj PreviewSecondDSideTrenchNeutral = new ChoreoTraj(
        "PreviewSecondDSideTrenchNeutral",
        OptionalInt.empty(),
        7.57175,
        new Pose2d(4.12706, 7.65828, Rotation2d.fromRadians(1.5708)),
        new Pose2d(3.3141, 5.37187, Rotation2d.fromRadians(0.5236))
    );

    /**
     * A map between trajectory names and their corresponding data.
     * This allows for trajectory data to be looked up with strings during runtime.
     */
    public static final Map<String, ChoreoTraj> ALL_TRAJECTORIES = Map.ofEntries(
        Map.entry("PreviewOSideTrenchNeutralOutpost", PreviewOSideTrenchNeutralOutpost),
        Map.entry("PreviewPreloadDepot", PreviewPreloadDepot),
        Map.entry("PreviewSecondOSideTrenchNeutral", PreviewSecondOSideTrenchNeutral),
        Map.entry("PreviewPreloadAndBackup", PreviewPreloadAndBackup),
        Map.entry("Preview4414DSideTrenchNeutral_copy1", Preview4414DSideTrenchNeutral_copy1),
        Map.entry("PreviewFirstDSideTrenchNeutral", PreviewFirstDSideTrenchNeutral),
        Map.entry("PreviewOSidePreloadAndBackup", PreviewOSidePreloadAndBackup),
        Map.entry("AutoPIDTuning", AutoPIDTuning),
        Map.entry("PreviewPreloadDepotOutpost", PreviewPreloadDepotOutpost),
        Map.entry("PreviewFirstOSideTrenchNeutral", PreviewFirstOSideTrenchNeutral),
        Map.entry("PreviewSecondDSideTrenchNeutral", PreviewSecondDSideTrenchNeutral)
    );

    /**
     * Looks up the ChoreoTraj segment of the given overall ChoreoTraj.
     * WARNING: will raise an exception if not called with a valid segment index.
     */
    public ChoreoTraj segment(int segment) {
        var traj = ChoreoTraj.ALL_TRAJECTORIES.get(this.name + "$" + segment);
        if (traj == null) {
            throw new NullPointerException("Trajectory " + this.name + " does not have segment #" + segment + ".");
        }
        return traj;
    }
    
    // If these methods cause errors because you're not using ChoreoLib,
    // turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
    /**
     * Load an AutoTrajectory directly from a ChoreoTraj, which may be a segment of a larger trajectory.
     */
    public AutoTrajectory asAutoTraj(AutoRoutine routine) {
        if (this.segment.isPresent()) {
            return routine.trajectory(this.name, this.segment.getAsInt());
        }
        return routine.trajectory(this.name);
    }
}
// spotless:on
